package migrations

import (
	migrate "github.com/rubenv/sql-migrate"
	"pon-relay.com/database/vars"
)

var Migration001InitDatabase = &migrate.Migration{
	Id: "001-init-database",
	Up: []string{`
		CREATE TABLE IF NOT EXISTS ` + vars.TableValidators + ` (

			validator_pubkey        varchar(98) NOT NULL,
			status INTEGER NOT NULL,
			report_count   INTEGER NOT NULL
		);

		CREATE UNIQUE INDEX IF NOT EXISTS ` + vars.TableValidators + `_pubkey ON ` + vars.TableValidators + `("validator_pubkey");


		CREATE TABLE IF NOT EXISTS ` + vars.TableExecutionPayload + ` (
			id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			inserted_at timestamp NOT NULL default current_timestamp,

			slot            bigint NOT NULL,
			proposer_pubkey varchar(98) NOT NULL,
			block_hash      varchar(66) NOT NULL,

			version     text NOT NULL, -- bellatrix
			payload 	json NOT NULL
		);

		CREATE UNIQUE INDEX IF NOT EXISTS ` + vars.TableExecutionPayload + `_slot_pk_hash_idx ON ` + vars.TableExecutionPayload + `(slot, proposer_pubkey, block_hash);

		DROP TABLE IF EXISTS ` + vars.TableBuilderBlockSubmission + `;
		CREATE TABLE IF NOT EXISTS ` + vars.TableBuilderBlockSubmission + ` (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			inserted_at timestamp NOT NULL default current_timestamp,
			signature            text NOT NULL,
			rpbs				 text NOT NULL,
			transactionByteString text NOT NULL,
			slot        bigint NOT NULL,
			builder_pubkey         varchar(98) NOT NULL,
			proposer_pubkey        varchar(98) NOT NULL,
			value  NUMERIC(48, 0),
			-- helpers
			epoch        bigint NOT NULL
		);

		CREATE INDEX IF NOT EXISTS ` + vars.TableBuilderBlockSubmission + `_slot_idx ON ` + vars.TableBuilderBlockSubmission + `("slot");
		CREATE INDEX IF NOT EXISTS ` + vars.TableBuilderBlockSubmission + `_builderpubkey_idx ON ` + vars.TableBuilderBlockSubmission + `("builder_pubkey");
		
		DROP TABLE IF EXISTS ` + vars.TableBlindedBeaconBlock + `;
		CREATE TABLE IF NOT EXISTS ` + vars.TableBlindedBeaconBlock + ` (
			id bigint 		GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			inserted_at 	timestamp NOT NULL default current_timestamp,
			signature       text NOT NULL,
			block_hash 		varchar(66) NOT NULL,
			proposer        text NOT NULL,
			slot        	bigint NOT NULL
		);
		CREATE INDEX IF NOT EXISTS ` + vars.TableBlindedBeaconBlock + `_slot_idx ON ` + vars.TableBlindedBeaconBlock + `("slot");

		CREATE TABLE IF NOT EXISTS ` + vars.TableDeliveredPayload + ` (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			inserted_at timestamp NOT NULL default current_timestamp,

			epoch bigint NOT NULL,
			slot  bigint NOT NULL,

			proposer_pubkey        varchar(98) NOT NULL,
			proposer_fee_recipient varchar(42) NOT NULL,

			parent_hash  varchar(66) NOT NULL,
			block_hash   varchar(66) NOT NULL,
			block_number bigint NOT NULL,

			gas_used  bigint NOT NULL,
			gas_limit bigint NOT NULL,

			UNIQUE (slot, proposer_pubkey, block_hash)
		);

		CREATE INDEX IF NOT EXISTS ` + vars.TableDeliveredPayload + `_slot_idx ON ` + vars.TableDeliveredPayload + `("slot");
		CREATE INDEX IF NOT EXISTS ` + vars.TableDeliveredPayload + `_blockhash_idx ON ` + vars.TableDeliveredPayload + `("block_hash");
		CREATE INDEX IF NOT EXISTS ` + vars.TableDeliveredPayload + `_blocknumber_idx ON ` + vars.TableDeliveredPayload + `("block_number");
		CREATE INDEX IF NOT EXISTS ` + vars.TableDeliveredPayload + `_proposerpubkey_idx ON ` + vars.TableDeliveredPayload + `("proposer_pubkey");
		
		CREATE TABLE IF NOT EXISTS ` + vars.TableDeliveredGetHeader + ` (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			inserted_at timestamp NOT NULL default current_timestamp,

			slot  bigint NOT NULL,
			proposer_pubkey        varchar(98) NOT NULL,
			value  NUMERIC(48, 0)
		);

		CREATE INDEX IF NOT EXISTS ` + vars.TableDeliveredGetHeader + `_slot_idx ON ` + vars.TableDeliveredGetHeader + `("slot");

		CREATE TABLE IF NOT EXISTS ` + vars.TableBlockBuilder + ` (

			builder_pubkey  varchar(98) NOT NULL PRIMARY KEY,
			status    	INTEGER NOT NULL
		);
		CREATE INDEX IF NOT EXISTS ` + vars.TableBlockBuilder + `_status ON ` + vars.TableBlockBuilder + `("status");

		CREATE TABLE IF NOT EXISTS ` + vars.TableReporters + ` (

			reporter_pubkey  varchar(98) NOT NULL PRIMARY KEY,
			active    	BOOLEAN NOT NULL,
			report_count INTEGER NOT NULL
		);
		CREATE INDEX IF NOT EXISTS ` + vars.TableReporters + `_pubkey ON ` + vars.TableReporters + `("reporter_pubkey");
		`},
	Down: []string{`
		DROP TABLE IF EXISTS ` + vars.TableBuilderBlockSubmission + `;
		DROP TABLE IF EXISTS ` + vars.TableDeliveredPayload + `;
		DROP TABLE IF EXISTS ` + vars.TableBlockBuilder + `;
		DROP TABLE IF EXISTS ` + vars.TableExecutionPayload + `;
		DROP TABLE IF EXISTS ` + vars.TableValidators + `;
		DROP TABLE IF EXISTS ` + vars.TableReporters + `;
		`},
	DisableTransactionUp:   false,
	DisableTransactionDown: false,
}
